version: 2
jobs:
  build-branch:
    docker:
      - image: node:8.9-alpine
  
    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "I am branch!"

  build-master:
    docker:
      - image: node:8.9-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn
      - run: BASE_BRANCH=$CIRCLE_BRANCH BASE_SHA=$CIRCLE_SHA1 node index.js

workflows:
  version: 2
  build:
    jobs:
      - build-branch:
          filters:
            branches:
              ignore: master
      - build-master:
          filters:
            branches:
              only: master
