version: 2
jobs:
  build-branch:
    docker:
      - image: node:8.9-alpine
  
    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "I am branch!"

  build-master:
    docker:
      - image: node:8.9-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "I am master!"
  


workflows:
  version: 2
  build:
    jobs:
      - build-branch
      - build-master:
          filters:
            branches:
              only: master
